export enum GenerationCategory {
  TEXT_TO_IMAGE = 'TEXT_TO_IMAGE',
  IMAGE_TO_IMAGE = 'IMAGE_TO_IMAGE',
  TEXT_TO_VIDEO = 'TEXT_TO_VIDEO',
  IMAGE_TO_VIDEO = 'IMAGE_TO_VIDEO',
  AUDIO_TO_VIDEO = 'AUDIO_TO_VIDEO',
  STORYBOARD_TO_VIDEO = 'STORYBOARD_TO_VIDEO',
  TEXT_TO_MUSIC = 'TEXT_TO_MUSIC',
  SPEECH_TO_TEXT = 'SPEECH_TO_TEXT',
  TEXT_TO_SPEECH_SINGLE = 'TEXT_TO_SPEECH_SINGLE',
  TEXT_TO_SPEECH_MULTIPLE = 'TEXT_TO_SPEECH_MULTIPLE',
}
